/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CsvManager;
import Control.Manager;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rauccin
 */
public class BuyerHome extends javax.swing.JFrame {
    private Manager m;
    private String percorsoFile;
    private ArrayList<String[]> dati;
    /**
     * Creates new form BuyerHome
     */
    public BuyerHome() {
        initComponents();
        m = new Manager();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setBackground(new java.awt.Color(121, 128, 238));
        jTable1.setRowHeight(30);
        
        // linee tabella
        jTable1.setShowGrid(true);
        jTable1.setGridColor(new java.awt.Color(200,200,200));

        // sfondo scrollpane
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        
        // bordo scrollpane
        jScrollPane1.setBorder(null);
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        jTable2.getTableHeader().setOpaque(true);
        jTable2.getTableHeader().setBackground(new java.awt.Color(121, 128, 238));
        jTable2.setRowHeight(30);
        
        // linee tabella
        jTable2.setShowGrid(true);
        jTable2.setGridColor(new java.awt.Color(200,200,200));

        // sfondo scrollpane
        jScrollPane2.getViewport().setBackground(java.awt.Color.WHITE);
        
        // bordo scrollpane
        jScrollPane2.setBorder(null);
        
    }
    
    private void caricaTabella(ArrayList<String[]> dati) {

        DefaultTableModel model = new DefaultTableModel();
        String[] colonne = {
            "Name", "Location", "Rooms", "Price",
            "Services", "Type", "Unavailability", "Reviews", "Owner"
        };
        model.setColumnIdentifiers(colonne);
        for (String[] riga : dati) {
            model.addRow(riga);
        }
        jTable1.setModel(model);
    }
    
    private void apriSelectCSV() {
        JFileChooser chooser = new JFileChooser();
        int scelta = chooser.showOpenDialog(this);
        
        if (scelta == JFileChooser.APPROVE_OPTION) {
            
            File file = chooser.getSelectedFile();
            percorsoFile = file.getAbsolutePath();
            dati = CsvManager.getDatiAlloggi();
            CsvManager.leggiCSV(percorsoFile, dati);
            caricaTabella(dati);
            m.caricaAlloggi();      
        }else {
            JOptionPane.showMessageDialog(this,"Nessun file selezionato!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Insert = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        EditText = new javax.swing.JMenuItem();
        research = new javax.swing.JMenu();
        ByLocation = new javax.swing.JMenuItem();
        ByPrice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(213, 227, 237));
        jTable1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Rooms", "Price", "Services", "Type", "Unavailability ", "Reviews", "Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(44, 15, 130));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(237, 227, 63));

        jLabel2.setBackground(new java.awt.Color(237, 213, 121));
        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUB B&B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
        );

        jTable2.setBackground(new java.awt.Color(213, 227, 237));
        jTable2.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Rooms", "Price", "Services", "Type", "Unavailability", "Reviews", "Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(44, 15, 130));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Bookings");

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Destinations");

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        Open.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Save.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        Exit.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        Insert.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Insert.setText("Add booking ");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        jMenu2.add(Insert);

        Delete.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jMenu2.add(Delete);

        EditText.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        EditText.setText("Edit booking");
        EditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTextActionPerformed(evt);
            }
        });
        jMenu2.add(EditText);

        jMenuBar1.add(jMenu2);

        research.setText("Research");
        research.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        ByLocation.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        ByLocation.setText("by location");
        ByLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByLocationActionPerformed(evt);
            }
        });
        research.add(ByLocation);

        ByPrice.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        ByPrice.setText("by price");
        ByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByPriceActionPerformed(evt);
            }
        });
        research.add(ByPrice);

        jMenuBar1.add(research);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        apriSelectCSV();
    }//GEN-LAST:event_OpenActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        //salvaCSV();
    }//GEN-LAST:event_SaveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        BuyerLogin login = new BuyerLogin();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        if (dati == null) {
            JOptionPane.showMessageDialog(this, "Carica prima il file!");
            return;
        }

        Insert ins = new Insert(this, true);
        ins.setVisible(true);

        String[] nuovo = ins.getDatiAggiornati();

        if (nuovo == null) return;
        dati.add(nuovo);
        ((DefaultTableModel) jTable1.getModel()).addRow(nuovo);
    }//GEN-LAST:event_InsertActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        //eliminaRiga();
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTextActionPerformed
        // TODO add your handling code here:
        //modificaRiga();
    }//GEN-LAST:event_EditTextActionPerformed

    private void ByLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByLocationActionPerformed
        // TODO add your handling code here:
        if (dati == null) {
            JOptionPane.showMessageDialog(this, "Carica prima il file!");
            return;
        }

        ByLocationBuyer ins = new ByLocationBuyer(this, true);
        ins.setVisible(true);
    }//GEN-LAST:event_ByLocationActionPerformed

    private void ByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByPriceActionPerformed
        // TODO add your handling code here:
        if (dati == null) {
            JOptionPane.showMessageDialog(this, "Carica prima il file!");
            return;
        }

        ByPriceBuyer ins = new ByPriceBuyer(this, true);
        ins.setVisible(true);
    }//GEN-LAST:event_ByPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ByLocation;
    private javax.swing.JMenuItem ByPrice;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem EditText;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Insert;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenu research;
    // End of variables declaration//GEN-END:variables
}
