/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author franc
 */
public class Edit extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Edit.class.getName());
    private String[] dati;
    private String recensioni;
    /**
     * Creates new form Edit
     */
    public Edit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        servizi = new javax.swing.JList<>();
        nome = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        camere = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Availability = new javax.swing.JList<>();
        prezzo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoAlloggio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SaveChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        servizi.setBackground(new java.awt.Color(213, 227, 237));
        servizi.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        servizi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(servizi);

        nome.setBackground(new java.awt.Color(213, 227, 237));
        nome.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        nome.setText("jTextField1");
        nome.addActionListener(this::nomeActionPerformed);

        location.setBackground(new java.awt.Color(213, 227, 237));
        location.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        location.setText("jTextField2");

        camere.setBackground(new java.awt.Color(213, 227, 237));
        camere.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        camere.setText("jTextField3");

        Availability.setBackground(new java.awt.Color(213, 227, 237));
        Availability.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Availability.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Availability);

        prezzo.setBackground(new java.awt.Color(213, 227, 237));
        prezzo.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        prezzo.setText("jTextField4");

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Location");

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Rooms");

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Price");

        tipoAlloggio.setBackground(new java.awt.Color(213, 227, 237));
        tipoAlloggio.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        tipoAlloggio.setText("jTextField4");
        tipoAlloggio.addActionListener(this::tipoAlloggioActionPerformed);

        jLabel5.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Type of accommodation");

        jLabel6.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Services");

        jLabel7.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Availability");

        jPanel1.setBackground(new java.awt.Color(121, 128, 238));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        SaveChanges.setBackground(new java.awt.Color(121, 128, 238));
        SaveChanges.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        SaveChanges.setText("Save changes");
        SaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveChangesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveChangesMouseExited(evt);
            }
        });
        SaveChanges.addActionListener(this::SaveChangesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tipoAlloggio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(prezzo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(camere, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(SaveChanges)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(camere, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoAlloggio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(SaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void tipoAlloggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlloggioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAlloggioActionPerformed

    private void SaveChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesMouseEntered
        // TODO add your handling code here
        SaveChanges.setBackground(new Color(213, 227, 237));
    }//GEN-LAST:event_SaveChangesMouseEntered

    private void SaveChangesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesMouseExited
        // TODO add your handling code here:
        SaveChanges.setBackground(new Color(121, 128, 238));
    }//GEN-LAST:event_SaveChangesMouseExited

    private void SaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesActionPerformed
        // TODO add your handling code here:
        getDatiAggiornati();
        this.dispose();
    }//GEN-LAST:event_SaveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {new Edit(null, true).setVisible(true);});
    }
    
    public void setDati(String[] datiRiga) {

        dati=datiRiga;
        
        nome.setText(datiRiga[0]);
        location.setText(datiRiga[1]);
        camere.setText(datiRiga[2]);
        prezzo.setText(datiRiga[3]);
        tipoAlloggio.setText(datiRiga[5]);

        // tolgo le graffe
        String serv = datiRiga[4].replace("{", "").replace("}", "").replace("\"", "");
        // divido gli elementi
        String[] elementi1 = serv.split(",");
        
        DefaultListModel<String> model1 = new DefaultListModel<>();
        for(String s : elementi1){
            model1.addElement(s);
        }
        servizi.setModel(model1);
        
        // tolgo le graffe
        String disp = datiRiga[6].replace("{", "").replace("}", "").replace("\"", "");
        // divido gli elementi
        String[] elementi2 = disp.split(",");
        
        DefaultListModel<String> model2 = new DefaultListModel<>();
        for(String s : elementi2){
            model2.addElement(s);
        }
        Availability.setModel(model2);
        
        recensioni=datiRiga[7];
    }
    
    public String[] getDatiAggiornati() {

        // aggiorno campi base
        dati[0] = nome.getText();
        dati[1] = location.getText();
        dati[2] = camere.getText();
        dati[3] = prezzo.getText();

        // LISTA SERVIZI
        List<String> selezionati1 = servizi.getSelectedValuesList();
        String serv = "{" + String.join(",", selezionati1) + "}";
        dati[4] = serv;

        dati[5] = tipoAlloggio.getText();
        
        // LISTA DATE
        List<String> selezionati2 = Availability.getSelectedValuesList();
        String available = "{" + String.join(",", selezionati2) + "}";
        dati[6] = available;
        
        dati[7] = recensioni;

        return dati;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Availability;
    private javax.swing.JButton SaveChanges;
    private javax.swing.JTextField camere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField prezzo;
    private javax.swing.JList<String> servizi;
    private javax.swing.JTextField tipoAlloggio;
    // End of variables declaration//GEN-END:variables
}
