/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author franc
 */
public class InsertVendor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InsertVendor.class.getName());
    /**
     * Creates new form Insert
     */
    public InsertVendor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveChanges = new javax.swing.JButton();
        prezzo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoAlloggio = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        camere = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SaveChanges.setBackground(new java.awt.Color(121, 128, 238));
        SaveChanges.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        SaveChanges.setText("Save changes");
        SaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveChangesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveChangesMouseExited(evt);
            }
        });
        SaveChanges.addActionListener(this::SaveChangesActionPerformed);

        prezzo.setBackground(new java.awt.Color(213, 227, 237));
        prezzo.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Services"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Unavailability"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Location");

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Rooms");

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Price");

        tipoAlloggio.setBackground(new java.awt.Color(213, 227, 237));
        tipoAlloggio.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        tipoAlloggio.addActionListener(this::tipoAlloggioActionPerformed);

        nome.setBackground(new java.awt.Color(213, 227, 237));
        nome.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        nome.addActionListener(this::nomeActionPerformed);

        jLabel5.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Type of accommodation");

        location.setBackground(new java.awt.Color(213, 227, 237));
        location.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        camere.setBackground(new java.awt.Color(213, 227, 237));
        camere.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(121, 128, 238));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(prezzo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(camere, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tipoAlloggio, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(SaveChanges)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(camere, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoAlloggio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(SaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesMouseEntered
        // TODO add your handling code here
        SaveChanges.setBackground(new Color(213, 227, 237));
    }//GEN-LAST:event_SaveChangesMouseEntered

    private void SaveChangesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesMouseExited
        // TODO add your handling code here:
        SaveChanges.setBackground(new Color(121, 128, 238));
    }//GEN-LAST:event_SaveChangesMouseExited

    private void SaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesActionPerformed
        // TODO add your handling code here:
        // NAME
        if (nome.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Name field cannot be empty!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);return;
        }
        // LOCATION
        if (location.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Location field cannot be empty!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ROOMS
        if (camere.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Rooms field cannot be empty!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Integer.parseInt(camere.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Rooms must be a number!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // PRICE
        if (prezzo.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Price field cannot be empty!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Double.parseDouble(prezzo.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Price must be a number!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // TYPE
        if (tipoAlloggio.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Accommodation type field cannot be empty!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // SERVICES
        javax.swing.table.DefaultTableModel model1 = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        boolean servizioValido = false;
        for (int i = 0; i < model1.getRowCount(); i++) {
            Object valore = model1.getValueAt(i, 0);
            if (valore != null && !valore.toString().trim().isEmpty()) {
                servizioValido = true;
                break;
            }
        }

        if (!servizioValido) {
            javax.swing.JOptionPane.showMessageDialog(this,"Insert at least one service!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // UNAVAILABILITY 
        javax.swing.table.DefaultTableModel model2 = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        boolean dataValida = false;
        for (int i = 0; i < model2.getRowCount(); i++) {
            Object valore = model2.getValueAt(i, 0);

            if (valore != null && !valore.toString().trim().isEmpty()) {
                String data = valore.toString().trim();
                for (int j = 0; j < data.length(); j++) {
                    char c = data.charAt(j);
                    if (!Character.isDigit(c) && c != '/') {
                        javax.swing.JOptionPane.showMessageDialog(this,"Invalid date: only numbers and '/' are allowed!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                dataValida = true;
            }
        }

        if (!dataValida) {
            javax.swing.JOptionPane.showMessageDialog(this,"Insert at least one date!","Input Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        getDatiAggiornati();
        this.dispose();
    }//GEN-LAST:event_SaveChangesActionPerformed

    private void tipoAlloggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlloggioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAlloggioActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InsertVendor dialog = new InsertVendor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public String[] getDatiAggiornati() {
        
        String recensioni = "";
        String[] dati = new String[8];
        dati[0] = nome.getText();
        dati[1] = location.getText();
        dati[2] = camere.getText();
        dati[3] = prezzo.getText();
        dati[5] = tipoAlloggio.getText();
        dati[7] = recensioni;

        // SERVICES
        javax.swing.table.DefaultTableModel model1 = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        String serv = "{";

        for (int i = 0; i < model1.getRowCount(); i++) {
            Object v = model1.getValueAt(i, 0);
            if (v != null && !v.toString().isEmpty()) {
                serv += v.toString();
                if (i < model1.getRowCount() - 1) serv += ",";
            }
        }

        serv += "}";

        dati[4] = serv;

        // UNAVAILABILITY
        javax.swing.table.DefaultTableModel model2 = (javax.swing.table.DefaultTableModel) jTable2.getModel();

        String disp = "{";

        for (int i = 0; i < model2.getRowCount(); i++) {
            Object v = model2.getValueAt(i, 0);
            if (v != null && !v.toString().isEmpty()) {
                disp += v.toString();
                if (i < model2.getRowCount() - 1) disp += ",";
            }
        }

        disp += "}";

        dati[6] = disp;

        return dati;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveChanges;
    private javax.swing.JTextField camere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField prezzo;
    private javax.swing.JTextField tipoAlloggio;
    // End of variables declaration//GEN-END:variables
}
