/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CsvManager;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rauccin
 */
public class VendorHome extends javax.swing.JFrame {
    private CsvManager g;
    /**
     * Creates new form VendorHome
     */
    public VendorHome() {
        initComponents();
        g = new CsvManager();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setBackground(new java.awt.Color(121, 128, 238));
        jTable1.getTableHeader().setForeground(java.awt.Color.WHITE);
        
        // linee tabella
        jTable1.setShowGrid(true);
        jTable1.setGridColor(new java.awt.Color(200,200,200));

        // sfondo scrollpane
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        
        // bordo scrollpane
        jScrollPane1.setBorder(null);
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    }
    
    private void caricaTabella(ArrayList<String[]> dati) {

        DefaultTableModel model = new DefaultTableModel();
        String[] colonne = {
            "Nome", "Località", "Camere", "Prezzo",
            "Servizi", "Tipo", "Disponibilità", "Recensioni", "Proprietario"
        };
        model.setColumnIdentifiers(colonne);
        for (String[] riga : dati) {
            model.addRow(riga);
        }
        jTable1.setModel(model);
    }
    
    private void apriSelectCSV() {

        JFileChooser chooser = new JFileChooser();
        int scelta = chooser.showOpenDialog(this);
        if (scelta == JFileChooser.APPROVE_OPTION) {

            File file = chooser.getSelectedFile();
            g.leggiCSV(file.getAbsolutePath());
            ArrayList<String[]> dati = g.getDati();
            caricaTabella(dati);

        } else {

            JOptionPane.showMessageDialog(this, "Nessun file selezionato!");
        }
    }
    
    private void eliminaRiga() {

        int riga = jTable1.getSelectedRow();

        if (riga == -1) {
            JOptionPane.showMessageDialog(this, "Seleziona una riga!");
            return;
        }

        g.delete(riga);

        // eliminazione grafica dalla tabella
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(riga);

        JOptionPane.showMessageDialog(this, "Elemento eliminato!");
    }
    
    private void modificaRiga() {
        int riga = jTable1.getSelectedRow();

        if (riga == -1) {
            JOptionPane.showMessageDialog(this, "Seleziona una riga!");
            return;
        }

        String nome = jTable1.getValueAt(riga, 0).toString();

        //apertura della casella di input
        
        
        CsvManager g = new CsvManager();
        //g.modificaElemento(nome);

        JOptionPane.showMessageDialog(this, "Modifica eseguita!");
    }
    
    private void salvaCSV() {

        CsvManager g = new CsvManager();
        //g.salva();

        JOptionPane.showMessageDialog(this, "CSV salvato!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Insert = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        EditText = new javax.swing.JMenuItem();
        Info = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();
        Credits = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(213, 227, 237));
        jTable1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(44, 15, 130));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(121, 128, 238));

        jLabel2.setBackground(new java.awt.Color(237, 213, 121));
        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUB B&B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(jLabel2)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        Open.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Save.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        Exit.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        Insert.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Insert.setText("Insert");
        jMenu2.add(Insert);

        Delete.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jMenu2.add(Delete);

        EditText.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        EditText.setText("EditText");
        EditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTextActionPerformed(evt);
            }
        });
        jMenu2.add(EditText);

        jMenuBar1.add(jMenu2);

        Info.setText("Info");
        Info.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N

        About.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        About.setText("About");
        Info.add(About);

        Credits.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        Credits.setText("Credits");
        Info.add(Credits);

        jMenuBar1.add(Info);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        VendorLogin login = new VendorLogin();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        eliminaRiga();
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTextActionPerformed
        // TODO add your handling code here:
        modificaRiga();
    }//GEN-LAST:event_EditTextActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        salvaCSV();
    }//GEN-LAST:event_SaveActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        apriSelectCSV();
    }//GEN-LAST:event_OpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendorHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Credits;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem EditText;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu Info;
    private javax.swing.JMenuItem Insert;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
