/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author franc
 */
public class Welcome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Welcome.class.getName());

    /**
     * Creates new form GUI
     */
    public Welcome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JPanel();
        WelcomeTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        WelcomeBuyer = new javax.swing.JPanel();
        BuyerLoginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        WelcomeVendor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        VendorLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Welcome.setBackground(new java.awt.Color(255, 255, 255));

        WelcomeTitle.setBackground(new java.awt.Color(195, 203, 244));

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WHO ARE YOU?");

        javax.swing.GroupLayout WelcomeTitleLayout = new javax.swing.GroupLayout(WelcomeTitle);
        WelcomeTitle.setLayout(WelcomeTitleLayout);
        WelcomeTitleLayout.setHorizontalGroup(
            WelcomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeTitleLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WelcomeTitleLayout.setVerticalGroup(
            WelcomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeTitleLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        WelcomeBuyer.setBackground(new java.awt.Color(239, 239, 255));

        BuyerLoginButton.setBackground(new java.awt.Color(51, 255, 0));
        BuyerLoginButton.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        BuyerLoginButton.setText("Login");
        BuyerLoginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        BuyerLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuyerLoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuyerLoginButtonMouseExited(evt);
            }
        });
        BuyerLoginButton.addActionListener(this::BuyerLoginButtonActionPerformed);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lato Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 66, 153));
        jLabel2.setText("Buyer");

        javax.swing.GroupLayout WelcomeBuyerLayout = new javax.swing.GroupLayout(WelcomeBuyer);
        WelcomeBuyer.setLayout(WelcomeBuyerLayout);
        WelcomeBuyerLayout.setHorizontalGroup(
            WelcomeBuyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeBuyerLayout.createSequentialGroup()
                .addGroup(WelcomeBuyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeBuyerLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(BuyerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WelcomeBuyerLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        WelcomeBuyerLayout.setVerticalGroup(
            WelcomeBuyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeBuyerLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(BuyerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WelcomeVendor.setBackground(new java.awt.Color(239, 239, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lato Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 66, 153));
        jLabel3.setText("Vendor");

        VendorLoginButton.setBackground(new java.awt.Color(51, 255, 0));
        VendorLoginButton.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        VendorLoginButton.setText("Login");
        VendorLoginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        VendorLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VendorLoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VendorLoginButtonMouseExited(evt);
            }
        });
        VendorLoginButton.addActionListener(this::VendorLoginButtonActionPerformed);

        javax.swing.GroupLayout WelcomeVendorLayout = new javax.swing.GroupLayout(WelcomeVendor);
        WelcomeVendor.setLayout(WelcomeVendorLayout);
        WelcomeVendorLayout.setHorizontalGroup(
            WelcomeVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeVendorLayout.createSequentialGroup()
                .addGroup(WelcomeVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeVendorLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(VendorLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WelcomeVendorLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        WelcomeVendorLayout.setVerticalGroup(
            WelcomeVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeVendorLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(VendorLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addComponent(WelcomeBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WelcomeVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(WelcomeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WelcomeBuyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Welcome.getAccessibleContext().setAccessibleName("Welcome");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VendorLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendorLoginButtonActionPerformed
        // TODO add your handling code here:
        VendorLogin login = new VendorLogin();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_VendorLoginButtonActionPerformed

    private void BuyerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerLoginButtonActionPerformed
        // TODO add your handling code here:
        BuyerLogin login = new BuyerLogin();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_BuyerLoginButtonActionPerformed

    private void BuyerLoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyerLoginButtonMouseExited
        // TODO add your handling code here:
        BuyerLoginButton.setBackground(new Color(51, 255, 0));
    }//GEN-LAST:event_BuyerLoginButtonMouseExited

    private void BuyerLoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyerLoginButtonMouseEntered
        // TODO add your handling code here
        BuyerLoginButton.setBackground(new Color(237, 227, 63));
    }//GEN-LAST:event_BuyerLoginButtonMouseEntered

    private void VendorLoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendorLoginButtonMouseEntered
        // TODO add your handling code here:
        VendorLoginButton.setBackground(new Color(121, 128, 238));
    }//GEN-LAST:event_VendorLoginButtonMouseEntered

    private void VendorLoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendorLoginButtonMouseExited
        // TODO add your handling code here:
        VendorLoginButton.setBackground(new Color(51, 255, 0));
    }//GEN-LAST:event_VendorLoginButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Welcome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyerLoginButton;
    private javax.swing.JButton VendorLoginButton;
    private javax.swing.JPanel Welcome;
    private javax.swing.JPanel WelcomeBuyer;
    private javax.swing.JPanel WelcomeTitle;
    private javax.swing.JPanel WelcomeVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
